apiVersion: v1
kind: Pod
metadata:
  name: test-fastapi-pod
  labels:
    app: test-fastapi
spec:
  containers:
    - name: test-fastapi
      image: lizatym/test_fastapi:latest
      ports:
        - containerPort: 80
